### ISSUE TITLE
amp calculation for cadiac recv

### ISSUE THREAD

**Issue by yhgon** [DavidDiazGuerra/gpuRIR#6]
I test cardiac recv with multiple direction. 

only `[1,1,0]` sound is normal but other directions, it include loud noise.
I guess some mis calculation of amp for cardiac recv. 
I didn't investigate the source code,  IMHO, during amp calculation for card recv,   not only vector direction but also vector length would be affects.
   
I'm include my test script and spectrogram analysis result
```
room_sz = [40,40,40]  # Size of the room [m]
import scipy.io.wavfile as wf
fs, source_signal = wavfile.read('pong.wav') # 3 sec w/ 22khz sound
nb_src = 1  # Number of sources
pos_src = np.array([ [10,10,0.3] ]) # Positions of the sources ([m]
nb_rcv = 1 # Number of receivers
pos_rcv = np.array([ [20,20,1.7]   ])	 # Position of the receivers [m]
orV_rcv = np.array([    [-1,0,0]  ] )  # Vectors pointing in the same direction than the receivers
mic_pattern = "card" # Receiver polar pattern
#fs=44100 # Sampling frequency [Hz]
beta = np.zeros(6) # Reflection coefficients
Tmax = 0.05	 # Time to stop the simulation [s]
Tdiff= Tmax  # Time to start the diffuse reverberation model [s]
nb_img = gpuRIR.t2n( Tdiff, room_sz )	# Number of image sources in each dimension
RIRs = gpuRIR.simulateRIR(room_sz, beta, pos_src, pos_rcv, nb_img, Tmax, fs, Tdiff=Tdiff, orV_rcv=orV_rcv, mic_pattern=mic_pattern)
RIRs.shape
RIRs
filtered_signal = gpuRIR.simulateTrajectory(source_signal, RIRs)
filtered_signal.shape
import numpy as np

#filtered_signal /=1.414
filtered_signal *= 32767
int16_data = filtered_signal.astype(np.int16)
wf.write("filtered_signal_recv_-1_0_0.wav", fs, int16_data)
```
stereo with  left [1,1,0],  right [-1,1,0] 
![image](https://user-images.githubusercontent.com/2494562/58646937-6dd06e80-8341-11e9-81d8-cad00c33da5b.png)

 direction[1,1,0] is normal
![image](https://user-images.githubusercontent.com/2494562/58648106-e9331f80-8343-11e9-879b-428c28b208d1.png)

direction[1,0,0]
![image](https://user-images.githubusercontent.com/2494562/58648224-3d3e0400-8344-11e9-8209-199d65f45ca1.png)

direction [-1,0,0]
![image](https://user-images.githubusercontent.com/2494562/58648355-79716480-8344-11e9-99ec-8cdfe88a8b3f.png)

**Comment by yhgon** [comment]
when I check the related position of src, rcv, direction
same direction for sound source works well.  and other direction have noisy output.

```
room_sz = [40,40,40]  # Size of the room [m]
import scipy.io.wavfile as wf
fs, source_signal = wavfile.read('pong.wav')
nb_src = 1  # Number of sources
pos_src = np.array([ [30,30,0.3] ]) # Positions of the sources ([m]
nb_rcv = 1 # Number of receivers
pos_rcv = np.array([ [20,20,1.7]   ])	 # Position of the receivers [m]
orV_rcv = np.array([    [1,1,0]  ] )  # Vectors pointing in the same direction than the receivers
mic_pattern = "card" # Receiver polar pattern
#fs=44100 # Sampling frequency [Hz]
beta = np.zeros(6) # Reflection coefficients
Tmax = 0.05	 # Time to stop the simulation [s]
Tdiff= Tmax  # Time to start the diffuse reverberation model [s]
nb_img = gpuRIR.t2n( Tdiff, room_sz )	# Number of image sources in each dimension
RIRs = gpuRIR.simulateRIR(room_sz, beta, pos_src, pos_rcv, nb_img, Tmax, fs, Tdiff=Tdiff, orV_rcv=orV_rcv, mic_pattern=mic_pattern)
RIRs.shape
RIRs
filtered_signal = gpuRIR.simulateTrajectory(source_signal, RIRs)
filtered_signal.shape
import numpy as np

#filtered_signal /=1.414
filtered_signal *= 32767
int16_data = filtered_signal.astype(np.int16)
wf.write("filtered_signal_recv_src_oposit_recv1_1_0.wav", fs, int16_data)
```

direction [1,1,0] have problem. 
that means aligned direction for cardiac recv  works well and other direction, a lot of noise effect. 

[-1,-1,0]  ( same direction works well) 
![image](https://user-images.githubusercontent.com/2494562/58649332-cf470c00-8346-11e9-8c37-f8a5f0118abd.png)

[1,1,0]
![image](https://user-images.githubusercontent.com/2494562/58649190-6b244800-8346-11e9-8d07-c75ead506d05.png)

**Comment by DavidDiazGuerra** [comment]
I think the problem is not that the directions different from [1,1,0] have noise, but that you are saturating the wav file. When you read or write a 16-bit PCM wav file with scipy, you are supposed to work with integers from -32768 to +32767, but if you write a signal with higher values scipy doesn't raise any warning (as Matlab would do) and just saturate the signals.

As your source signal is read with scipy, it is already in the range [-32768, +32767], so you don't need to multiply by 32767. Direction [1,1,0] seems to be working because it's so close to the null of the cardioid that it's so attenuated that it doesn't saturate the wav. I think that if you remove the line `filtered_signal *= 32767` your issue should be solved.

Please, let me know if it worked.

**Comment by yhgon** [comment]
@DavidDiazGuerra  You are right. w/o multiply, sound looks good. 

two thing. 
1.  no significant difference of cardioid recv direction.  
for example, `orV_rcv = np.array([  [0,1,0],   [-1,-1,0]  ] ) `  opposite direction sound is almost same. 

1. if the distance of (source,recv) is larger that 20m, received value were  be zoro.   
```
pos_src = np.array([ [1,20,0.3] ]) # Positions of the sources ([m]
nb_rcv = 2 # Number of receivers
pos_rcv = np.array([[20,20,1.7],[20,20,1.7]   ])	 # Position of the receivers [m]
orV_rcv = np.array([  [0,1,0],   [-1,-1,0]   ] )  # Vectors pointing in the same direction than the receivers
mic_pattern = "card" # Receiver polar pattern
```
Do you have any idea?

**Comment by DavidDiazGuerra** [comment]
1. In an anechoic chamber, the only difference I would expect is [-1,-1,0] having more amplitude (actually, no microphone is 100% cardioid for all the frequencies so you could expect more differences in the real world, but the library only simulate frequency independent patterns). If you increase `beta`, more differences should appear since the amplitude of each individual reflexion will be different. Anyway, though they will be there if you plot the signals and zoom in quite a lot, I don't think you will be able to hear them.
2.  What value of `Tmax` are you using? you must take into account that, for a distance larger than 20m, sound waves will need more than `20 / 343 = 0.0583` seconds to reach the microphone.

**Comment by yhgon** [comment]
thanks for your comment. @DavidDiazGuerra  

#2.  Tmax works well. however, I still have problem for #1 for cardioid direction. 

before check the reflection, I just calculate direct image from source to recv. and compare the result
when I assume one simple configuration, 
```
    room size	  recv position     src position
([120, 100, 40], [60.0, 40, 1.7])   [70.0, 22.68, 0.4]
```
mic1 and mic2 for cardioid mic for different direction on same position. 
 - distance between src and recv is  20m,  and delta of mic1 and mic2 is 0. 
 - with orthogonal direction, ( directionality would be 85 degree and -15 degree)  
 - `-15` degree : 0.98 dB : almost same direction
 - '85` degree : 0.54 dB : almost flat direction. 
 - cardioid polar result would be  0.54 dB and 0.98 dB 

so delta of  amplitude between two recv. would be bigger than simulated one.

**Comment by DavidDiazGuerra** [comment]
What values of `orV_rcv` are you using?
